defaults:
  - values:
      layout: default

  - scope:
      path: ''
      type: posts
      values:
      layout: blost

collections:
  projects:
    output: true
  research:
    output: true

permalink: pretty
